#!/usr/bin/env python3
"""Rebuild the static reconstruction. Standard library only; no network or npm.
This is newly written source, NOT an export of the unavailable ChatGPT Site.
Edit config.json and this file; then run python3 src/build.py from the project.
"""
from pathlib import Path
from html import escape
import json
import re

ROOT = Path(__file__).resolve().parents[1]
CONFIG = json.loads((ROOT / 'config.json').read_text())
PAGES = {}
ROUTE = ''
E = escape
ARROW = '<svg class="arrow" viewBox="0 0 24 24" aria-hidden="true"><path d="M5 19 19 5M5 5h14v14"/></svg>'
CHECK = '<svg class="check" viewBox="0 0 20 20" aria-hidden="true"><path d="m4 10 4 4 8-9"/></svg>'
NCCIH = 'https://www.nccih.nih.gov/health/meditation-and-mindfulness-effectiveness-and-safety'
NIMH = 'https://www.nimh.nih.gov/health/topics/psychotherapies'
EMAIL = CONFIG['email']

CONCERNS = [
 ('anxiety-stress','Anxiety & stress','When your mind will not slow down.','Make room between the pressure you feel and the choice you make next.','pool', ['What keeps interrupting your rest or concentration?','When do you feel most under pressure?','What would feel different if you had more support?']),
 ('depression','Depression','When getting through the day feels heavy.','Find a place to be honest, build structure, and move one step at a time.','contact', ['What has become harder to do or enjoy?','What do you wish you did not have to explain?','What is one part of daily life you would like help with?']),
 ('trauma','Trauma','When the past still feels close.','Move at a pace centered on safety, trust, and your goals.','approach', ['What would help you feel safer in a conversation?','Are there topics you are not ready to discuss?','What preferences or boundaries should your clinician know?']),
 ('grief-change','Grief & change','When life changed before you were ready.','Make space for what was lost—and for what may come next.','water', ['What has changed in your life?','What do people around you not seem to understand?','What kind of support would feel useful now?']),
 ('relationships','Relationships','When the same conversation keeps hurting.','Work on communication, boundaries, repair, and connection.','in-person', ['Which patterns do you keep returning to?','What would you like to be able to say more clearly?','What does a more workable relationship look like to you?']),
 ('substance-use','Substance use','When you want change without shame.','Explore support for recovery, change, and the people beside you.','approach', ['What are you hoping to change?','What kind of support have you already tried?','What would make asking for help feel more possible?']),
 ('life-transitions','Life transitions','When no one prepared you for this chapter.','Talk through caregiving, aging, identity, health changes, and transition.','at-home', ['What new role or responsibility are you adjusting to?','What do you miss about how things were?','Where would more support make a practical difference?'])
]
ARTICLES = [
 {'slug':'a-90-second-pause-when-worry-takes-over','title':'A 90-second pause when worry takes over','category':'Anxiety','image':'water','intro':'A small place to put your attention when your thoughts seem to be moving faster than the room around you.','sections':[
  ('Begin with the room, not the whole problem.','You do not have to solve the worry before you are allowed to take a moment. Try sitting or standing somewhere safe. Keep your eyes open if that feels more comfortable. Choose one ordinary detail in front of you: the edge of a table, a familiar color, or the light on the floor.'),
  ('Make the next minute smaller.','For roughly thirty seconds, let your attention return to that one detail. Then notice where your body is supported by a chair, the floor, or another surface. There is no special breathing pattern to get right. For the last part of the pause, ask yourself: “What is the next small thing in front of me?” That might be getting a glass of water, writing down one question, or telling someone that you need support.'),
  ('A pause is not a promise.','Nothing has to feel transformed at the end. A brief exercise is a choice, not a test you pass by feeling calm. Stop if the exercise feels uncomfortable. If worry is interfering with daily life, bring that experience to a qualified health professional rather than relying on a website exercise alone.')], 'source':NCCIH},
 {'slug':'when-focusing-on-your-breath-feels-worse','title':'When focusing on your breath feels worse','category':'Grounding','image':'pool','intro':'You do not have to use your breath as an anchor. Start with something outside yourself instead.','sections':[
  ('You are allowed to stop.','An exercise that feels uncomfortable does not become more useful because you force yourself to finish it. Let your breathing return to its own rhythm. Open your eyes, change position, or leave the exercise entirely. Your response is information, not a personal failure.'),
  ('Choose a neutral detail.','Look for something ordinary in the space around you: a window frame, the color of a mug, a quiet sound, or the feeling of the chair beneath you. You can name the detail silently and move on. Skip any sensation that feels difficult or unavailable to you.'),
  ('Bring the experience into the conversation.','You could tell a clinician, “Focusing on breathing makes me feel more uncomfortable. Can we try a different approach?” Mindfulness practices are not one-size-fits-all. NCCIH notes that some people have negative experiences with meditation and mindfulness and advises against using them to replace or delay conventional care.')], 'source':NCCIH},
 {'slug':'five-senses-grounding-when-thoughts-race','title':'Five-senses grounding when thoughts race','category':'Grounding','image':'contact','intro':'A flexible way to notice what is around you—without having to empty your mind.','sections':[
  ('A sequence, not a rule.','This exercise gives you a few small things to notice in a safe, familiar space. It is not a treatment or a guarantee of relief. You can stop, skip steps, repeat a step, or choose a different sense. Keep your breathing natural.'),
  ('Notice at your own pace.','Look for five things you can see. Notice four comfortable points of contact, such as your feet on the floor or fabric on your skin. Listen for three sounds. Choose two familiar scents—or two colors instead. Finally, notice a taste already present, or rest your attention on one neutral object. You do not need to eat, drink, or search for a sensation that is uncomfortable.'),
  ('Adapt the exercise to you.','There is no prize for finishing the sequence. Sensory differences, disability, and your preferences all belong in the exercise. The guided grounding tool lets you move through the steps manually. If focusing on sensations increases distress, stop and choose another kind of support.')], 'source':None},
 {'slug':'finding-words-for-a-first-session','title':'Finding words for a first session','category':'Therapy','image':'approach','intro':'You do not need a complete history or a polished explanation to begin a conversation.','sections':[
  ('Start with a sentence that is true.','“I am not sure where to begin.” “I have been more tired than usual.” “The same argument keeps happening.” “Something has felt different, and I want help understanding it.” These are possible openings—not a script you have to use. Choose the words that sound like you.'),
  ('Write down what you want to remember.','Before an appointment, you might note what has become harder, what you hope support could change, and what would help you feel comfortable in the room. A short note can also include questions about the clinician’s approach, privacy, session format, fees, and what happens if the match does not feel right.'),
  ('Leave room for questions.','A first conversation can be a chance to discuss goals and ask how the therapist works. You are allowed to say that you need more time, that a question is unclear, or that you are not ready to talk about a particular experience. For background on psychotherapy and questions to ask a prospective provider, see the NIMH resource below.')], 'source':NIMH},
 {'slug':'making-space-for-at-home-therapy','title':'Making a little space for at-home therapy','category':'Therapy','image':'at-home','intro':'The room does not need to be perfect. A few practical questions can make the setup clearer.','sections':[
  ('Think about privacy before the appointment.','Where can you talk without being overheard or interrupted? Are headphones useful in that space? Could notifications be silenced for the appointment? If a private room is not available, tell the clinician rather than feeling you have to pretend the setup works.'),
  ('Ask about the connection and the backup plan.','Confirm which platform to use, how the appointment link arrives, and what happens if the video connection fails. Ask whether you should call, wait for a new link, or use another approved method. Discuss any accessibility needs before the session when possible.'),
  ('Set aside time that belongs to the conversation.','Consider leaving a few minutes before the appointment to settle in and a few minutes afterward before the next task. Bring water, your questions, or a notebook if useful. Confirm that the clinician is authorized to provide care where you will be physically located during the session.')], 'source':None},
 {'slug':'when-you-do-not-feel-like-yourself','title':'When you do not feel like yourself','category':'Therapy','image':'pool','intro':'You can describe what has changed without deciding on a label first.','sections':[
  ('Begin with what you have noticed.','Instead of trying to choose a diagnosis, think about the changes you can describe in your own words. Perhaps conversations take more effort, routines feel harder, or you are avoiding things you used to make time for. Write down what feels true without turning it into a verdict about yourself.'),
  ('Be specific about the everyday impact.','You could ask yourself: What is taking more energy? What do I find myself putting off? When did I first notice a change? What have I already tried? You do not have to answer everything at once. These are notes for a conversation, not a screening test.'),
  ('Make room for professional support.','A qualified professional can help assess what is happening and discuss appropriate next steps. A website cannot determine the cause of a change in mood, energy, or functioning. New or concerning physical symptoms also deserve medical attention. In an emergency, seek urgent help rather than waiting for a routine appointment.')], 'source':None},
 {'slug':'making-room-for-grief','title':'Making room for grief, without a script','category':'Life','image':'contact','intro':'A few words to bring into a conversation when other people’s expectations do not fit your experience.','sections':[
  ('Say what the loss has changed.','There may be a person, relationship, role, routine, or imagined future you miss. You can talk about the practical changes as well as the feelings. “Mornings feel different now.” “I do not know how to answer when people ask how I am.” “I miss having someone to call.” Start wherever the experience feels most real.'),
  ('Ask for the kind of company you need.','You might want someone to listen, help with an errand, sit nearby, or stop offering advice for a while. Consider a simple request: “Could you listen without trying to make this better?” or “Can you check in with me next week?” Use your own language; these are examples, not obligations.'),
  ('Bring the unfinished parts.','A conversation does not need a lesson, a timeline, or a tidy ending. You can bring mixed feelings and unanswered questions to therapy. The starting point is not how someone else believes you should be doing. It is what life feels like for you, and what support would be useful now.')], 'source':None},
 {'slug':'a-pause-before-the-same-conversation','title':'A pause before the same conversation','category':'Life','image':'in-person','intro':'A reflection prompt for naming what you need before returning to a familiar disagreement.','sections':[
  ('Notice the conversation you are expecting.','Before a difficult conversation, write down the response you are preparing for. Then separate what you know from what you are predicting. You do not have to prove the prediction wrong. The purpose is simply to see which part of the conversation has already begun in your mind.'),
  ('Choose one thing to communicate.','What do you want the other person to understand? What request or boundary would be specific enough to act on? “I need us to choose a time when we are not rushing” may be easier to discuss than trying to explain every past disagreement at once. Your own situation may call for a different starting point.'),
  ('Keep safety in the picture.','A conversation exercise is not appropriate for every situation. If you are afraid of someone’s reaction or there is coercion, abuse, or immediate danger, prioritize safety and qualified support rather than treating the situation as an ordinary communication problem. You do not need to manage another person’s harmful behavior by finding the perfect words.')], 'source':None}
]

def prefix():
    return '../' * len(ROUTE.split('/')) if ROUTE else './'

def url(route=''):
    if route.startswith(('https://','http://','mailto:','tel:','sms:')): return route
    if '#' in route:
        path, fragment = route.split('#',1)
    else: path,fragment=route,''
    result = prefix() + ((path.strip('/') + '/') if path.strip('/') else '') + 'index.html'
    return result + ('#'+fragment if fragment else '')

def asset(name): return prefix() + name

def a(text, route, cls='text-link', arrow=True, attrs=''):
    external = ' target="_blank" rel="noopener noreferrer"' if route.startswith('https://') else ''
    return f'<a class="{cls}" href="{E(url(route),quote=True)}"{external} {attrs}>{text}{ARROW if arrow else ""}</a>'

def quiz_button(text='Take the quiz', cls='button', arrow=True):
    return a(text,CONFIG['quiz_url'],cls,arrow)

def eye(text, cls=''):
    return f'<span class="eyebrow {cls}">{text}</span>'

def image(name, alt, cls='', eager=False, attrs=''):
    dims = next((i for i in ASSETS if i['asset']==f'assets/images/{name}.webp'),{})
    wh = f' width="{dims.get("width",900)}" height="{dims.get("height",650)}"'
    loading='fetchpriority="high" loading="eager"' if eager else 'loading="lazy"'
    return f'<img src="{asset("assets/images/"+name+".webp")}" alt="{E(alt,quote=True)}" class="{cls}" {loading} decoding="async"{wh} {attrs}>'

def brand():
    return f'<a class="brand" href="{url()}" aria-label="Doppler Wellness home"><img src="{asset("assets/mark.svg")}" alt="" width="39" height="39"><span class="wordmark"><strong>DOPPLER</strong><small>WELLNESS</small></span></a>'

def nav():
    care_routes=['care','our-approach','mindfulness','at-home-therapy','in-person-therapy','insurance','questions']
    care_active=ROUTE in care_routes or ROUTE.startswith('care/')
    menu_links=[('Our approach','our-approach'),('Mindfulness','mindfulness'),('At-home therapy','at-home-therapy'),('In-person therapy','in-person-therapy'),('What we help with','care'),('Insurance','insurance'),('Questions','questions')]
    def nav_link(label,r):
        current=' aria-current="page"' if ROUTE==r else ''
        return f'<a class="nav-link" href="{url(r)}"{current}>{label}</a>'
    dropdown=''.join(f'<a href="{url(r)}">{label}{ARROW}</a>' for label,r in menu_links)
    return f'''<a class="skip" href="#main">Skip to content</a>
<header class="site-header"><div class="nav-shell">{brand()}
<nav class="nav-links" id="main-navigation" aria-label="Main navigation" data-main-nav>
{nav_link('Home','')}<details class="care-menu {'active' if care_active else ''}"><summary>Care <span aria-hidden="true">+</span></summary><div class="care-dropdown">{dropdown}</div></details>
{nav_link('Mission','mission')}{nav_link('Tools','tools')}{nav_link('Journal','journal')}{nav_link('For clinicians','for-clinicians')}{nav_link('Contact','contact')}
</nav>{quiz_button(cls='button nav-cta')}<button class="menu-toggle" type="button" aria-label="Open navigation" aria-controls="main-navigation" aria-expanded="false" data-menu-toggle><span></span><span></span></button>
</div></header>'''

def crisis():
    return f'''<section class="crisis-strip" aria-label="Immediate support"><div class="wrap crisis-inner"><div><strong>Need support right now?</strong><p>In the U.S., call 911 if you or someone else is in immediate danger. Doppler is not an emergency service.</p></div><div class="crisis-actions">{a('Call 988','tel:988','button outline',False)}{a('Text HOME to 741741','sms:741741','button outline',False)}</div></div></section>'''

def footer():
    def col(title,links):
        return f'<div><span class="footer-title">{title}</span><div class="footer-links">'+''.join(a(label,r,'',False) for label,r in links)+'</div></div>'
    return crisis()+f'''<footer class="site-footer"><div class="wrap"><div class="footer-invitation"><div>{eye('You do not need a perfect reason')}<h2>Start with what feels true today.</h2><p>The quiz is a first step, not a diagnosis. It helps Doppler begin the matching process. Eligibility and therapist availability vary.</p></div>{quiz_button()}</div><div class="footer-main"><div>{brand()}<p>Mindfulness-informed mental wellness care with at-home and in-person options.</p><p class="spaced">Eligibility and availability depend on age, location, and a clinician licensed to provide care where you are.</p></div>
{col('Care',[('Our approach','our-approach'),('Mindfulness','mindfulness'),('Mindfulness tools','tools'),('At-home therapy','at-home-therapy'),('Insurance','insurance'),('Questions','questions')])}
{col('Doppler',[('Mission','mission'),('For clinicians','for-clinicians'),('Journal','journal'),('Contact','contact')])}
<div><span class="footer-title">Connect</span><div class="footer-links">{a(EMAIL,'mailto:'+EMAIL,'footer-email',False)}{a('Patient intake',CONFIG['patient_intake_url'],'',False)}{a('Clinician application',CONFIG['clinician_application_url'],'',False)}</div></div></div><div class="footer-bottom"><p>© 2026 Doppler Wellness · Confirm eligibility, location, availability, and insurance participation before care.</p><div>{a('Website privacy','privacy','',False)}{a('Accessibility','accessibility','',False)}</div></div></div></footer>'''

def ready():
    return f'''<section class="section"><div class="wrap ready-panel"><div>{eye('Ready when you are')}<h2>Let’s find someone you can <em>actually talk to.</em></h2></div><div><p>Start with a few questions about what has been difficult, how you prefer to work, and where care fits best.</p><div class="actions">{quiz_button('Start the matching questionnaire','button yellow')}</div></div></div></section>'''

def subhero(title,copy,label,img='approach',tone='',caption='CONTEXT FIRST / PERSON ALWAYS',cta=None):
    action=cta if cta is not None else quiz_button()
    visual=f'<div class="hero-frame">{image(img,"Illustrative Doppler wellness scene",eager=True)}<div class="frame-caption"><span>{caption}</span><span>DOPPLER WELLNESS</span></div></div>' if img else ''
    return f'<section class="subhero {tone} {"text-hero" if not img else ""}"><div class="wrap"><div>{eye(label,"dot")}<h1>{title}</h1><p class="lead">{copy}</p><div class="actions">{action}</div></div>{visual}</div></section>'

def card_grid(cards):
    return '<div class="card-grid">'+''.join(f'<article class="info-card"><span class="number">0{i+1}</span><h3>{h}</h3><p>{p}</p></article>' for i,(h,p) in enumerate(cards))+'</div>'

def faqs(items):
    return '<div class="faq-list">'+''.join(f'<details><summary>{h}</summary><p>{p}</p></details>' for h,p in items)+'</div>'

FAQ = [
 ('How does the matching process begin?','Start with Doppler’s questionnaire. Your needs and preferences help shape a starting point, together with practical considerations such as age, location, eligibility, availability, and insurance.'),
 ('Can I meet at home or in person?','Both formats are part of Doppler’s care approach. Actual options depend on where you are, the clinician’s licensure and availability, and the type of support you need. Confirm the details before scheduling.'),
 ('Do I need to know exactly what I need?','You can begin by describing what has become harder and what you would like support with. The website quiz does not diagnose a condition or promise a particular therapist match.'),
 ('What should I ask about cost?','Ask about the clinician’s network status, your deductible, copay or coinsurance, any self-pay rate, and whether telehealth is covered. Coverage is specific to your plan and provider; it should be confirmed before care.'),
 ('How does virtual-care privacy work?','Ask which platform will be used, what privacy practices apply, where you can join privately, and what happens if the connection drops. Use the patient intake form for care-related information rather than ordinary email.'),
 ('Do I have to practice mindfulness?','The site offers optional breathing, grounding, reflection, and quiet-time tools. You can skip or stop any exercise. Talk with your clinician about what is appropriate for your care.'),
 ('What if the match does not feel right?','Tell the Doppler team or your clinician what is not working. Ask about the options for a different starting point. A meaningful conversation about fit is part of choosing care.'),
 ('Is this an emergency service?','No. In the U.S., call 911 for an immediate emergency. For crisis support, call or text 988. You can also text HOME to 741741. Do not wait for an intake response when you need urgent help.')
]

def mini_quiz():
    return f'''<div class="mini-quiz" data-mini-quiz aria-label="Find your starting point">{eye('A calm place to begin')}<p class="quiz-note">Three gentle taps · about 30 seconds</p><span class="eyebrow" data-quiz-step>Step 1 of 3</span><div class="quiz-progress" data-quiz-progress aria-hidden="true"><span class="on"></span><span></span><span></span></div><h2 data-quiz-heading>What would feel most helpful right now?</h2><div class="quiz-choices" data-quiz-choices></div><div class="quiz-result" data-quiz-result hidden><p data-quiz-summary></p>{quiz_button('Continue to the questionnaire','button small-button')}</div><div class="quiz-controls"><button class="quiet-button" type="button" data-quiz-back hidden>Back</button><button class="quiet-button" type="button" data-quiz-reset>Start over</button></div></div>'''

def concern_cards(rail=False):
    cards=''.join(f'<a class="concern-card" href="{url("care/"+slug)}"><div class="card-top">{eye(label)}{ARROW}</div><h3>{heading}</h3><p>{copy}</p></a>' for slug,label,heading,copy,_,_ in CONCERNS)
    return f'<div class="concern-rail" id="concern-rail" data-rail tabindex="0" aria-label="Topics you can explore">{cards}</div>' if rail else f'<div class="flat-conditions">{cards}</div>'

def match_panel():
    tabs=[('What you’re carrying','Start with what has become harder.','The concerns, patterns, experiences, and goals you choose to share help create a clearer starting point.'),('How you want to work','Make room for the way you open up.','Some people want space to process. Others want practical direction. Your preferences belong in the conversation.'),('What care must fit around','The practical details matter, too.','Discuss your location, the format you prefer, scheduling needs, eligibility, and coverage before care begins.')]
    tab_html=''.join(f'<button class="tab" type="button" role="tab" id="match-tab-{i}" aria-controls="match-panel-{i}" aria-selected="{str(i==0).lower()}" tabindex="{0 if i==0 else -1}">{h}</button>' for i,(h,_,_) in enumerate(tabs))
    panels=''.join(f'<div class="tab-panel" role="tabpanel" id="match-panel-{i}" aria-labelledby="match-tab-{i}" {"hidden" if i else ""}>{eye(h)}<h4>{t}</h4><p>{p}</p></div>' for i,(h,t,p) in enumerate(tabs))
    return f'<div class="match-panel" data-tabs>{eye("A considered starting point")}<h3>Not an endless directory.</h3><div class="tabs" role="tablist" aria-label="What shapes your starting point">{tab_html}</div>{panels}</div>'

def settings():
    return f'''<div class="care-setting" data-setting><div class="setting-copy">{eye('Care setting','purple')}<h3>Where would conversation feel most possible?</h3><div class="segmented" role="tablist" aria-label="Choose a care setting"><button type="button" id="setting-home" role="tab" aria-selected="true" aria-controls="setting-panel-home" data-setting-choice="home">At home</button><button type="button" id="setting-person" role="tab" aria-selected="false" tabindex="-1" aria-controls="setting-panel-person" data-setting-choice="person">In person</button></div>
<div class="setting-details" id="setting-panel-home" role="tabpanel" aria-labelledby="setting-home" data-setting-panel="home">{eye('At home')}<h4>Your own room.<br>Time set aside for you.</h4><p>Meet by secure video without adding a commute or another transition to the day.</p>{a('Explore at-home therapy','at-home-therapy')}</div>
<div class="setting-details" id="setting-panel-person" role="tabpanel" aria-labelledby="setting-person" data-setting-panel="person" hidden>{eye('In person')}<h4>A separate space.<br>A conversation just for you.</h4><p>Meet in person where location and clinician availability make it possible.</p>{a('Explore in-person therapy','in-person-therapy')}</div></div>
<div class="setting-image">{image('at-home','Illustrated man meeting a therapist by video from a warm room at home',attrs=f'data-setting-image data-home="{asset("assets/images/at-home.webp")}" data-person="{asset("assets/images/in-person.webp")}"')}</div></div>'''

def breath_tool():
    return f'''<div class="breath-tool" data-breath-tool><div class="tool-bar"><div class="tool-brand"><span class="tool-icon" aria-hidden="true"></span><span><strong>Doppler Pause</strong><small>GUIDED BREATHING</small></span></div><span class="pill"><i></i>Silent by default</span></div><div class="tool-body"><div class="breath-visual" aria-hidden="true"><div class="breath-orbits"><i class="orbit"></i><i class="orbit"></i><i class="orbit"></i><div class="orb"></div></div><span class="visual-cue" data-breath-visual-cue>Follow at a comfortable pace.</span></div><div class="tool-copy">{eye('A small reset, right where you are')}<h3 data-breath-cue aria-live="polite" aria-atomic="true">Take one easy breath.</h3><p>Follow the light at a comfortable pace. There is no need to breathe more deeply than feels natural.</p><div class="tool-options"><label class="sr-only" for="breath-duration">Practice duration</label><select id="breath-duration" data-breath-duration><option value="60">About one minute</option><option value="30">About 30 seconds</option></select><label class="checkbox-label"><input type="checkbox" data-breath-text> Text cues only</label></div><div class="tool-controls"><button class="button" type="button" data-breath-start>Start breathing</button><button class="button outline" type="button" data-breath-reset>Reset</button></div><progress class="tool-progress" max="60000" value="0" data-breath-progress aria-label="Practice progress"></progress><div class="tool-status" data-breath-status>Ready when you are.</div><div class="tool-secondary">{a('Use grounding instead','tools/grounding')}</div></div></div><div class="tool-footer"><p>Optional, general-wellness practice—not treatment. Stop if you feel uncomfortable or lightheaded. Keep your eyes open if that feels better.</p>{a('Choose another anchor','tools')}</div></div>'''

def pause_section():
    return f'''<section class="pause-section" id="pause"><div class="wrap">{eye('Try the kind of pause we mean')}<div class="pause-head"><div>{eye('A practice for the moments between','dot')}<h2>Notice sooner.<br>Create a pause.<em>Choose what follows.</em></h2></div><p>When it fits your care, grounding, breathing, reflection, or meditation can help turn insight into something usable. Follow the light at a comfortable pace, or choose another anchor.</p></div>{breath_tool()}<div class="below-tool"><p>Prefer another anchor?</p>{a('Explore all mindfulness tools','tools')}</div></div></section>'''

def journal_cards(items,home=False):
    content=''
    for item in items:
        content+=f'''<article class="article-card" data-journal-card data-category="{item['category']}"><a href="{url('journal/'+item['slug'])}"><div class="article-image">{image(item['image'],'Illustrative scene for '+item['title'])}<span class="round-button">{ARROW}</span></div><div class="article-meta"><span>{item['category']}</span><span>Short guide</span></div><h3>{item['title']}</h3></a>{'' if home else '<p>'+item['intro']+'</p>'}</article>'''
    return f'<div class="article-grid {"home-articles" if home else "full"}">{content}</div>'

def home():
    hero=f'''<section class="hero"><div class="hero-art">{image('pool','Illustrated woman seated beside a quiet indoor pool in a botanical courtyard',eager=True)}</div><div class="wrap hero-inner"><div class="hero-copy">{eye('Personal therapy, thoughtfully matched','dot')}<h1>Therapy, with <em>room to breathe.</em></h1><p class="lead">Finding help should not feel like another job. Tell Doppler what has been hard, how you want to be supported, and where therapy fits best. We’ll help you start with a therapist selected around more than an open appointment.</p><div class="actions">{quiz_button('Help me find the right therapist')}{a('Try a 60-second pause','#pause')}</div><div class="hero-welcome"><span>{CHECK}</span> A starting point shaped around you.</div></div>{mini_quiz()}</div></section>'''
    proof='<div class="proof-strip"><div class="wrap proof-grid">'+''.join(f'<div class="proof-item">{CHECK}<span>{x}</span></div>' for x in ['Thoughtful therapist matching','At home or in person','Mindfulness when it helps','Clear next steps'])+'</div></div>'
    before=f'''<section class="section"><div class="wrap"><div class="section-head"><div class="intro-head">{eye('Before the label','dot')}<h2>You may not know what to call it.<br><em>You know what it has been costing you.</em></h2><p class="lead">Sleep. Patience. Focus. Energy. Connection. Sometimes the clearest place to start is not a diagnosis—it is noticing what has become harder.</p></div><div class="rail-nav"><button class="round-button previous" type="button" data-scroll-rail="concern-rail" data-direction="-1" aria-label="Previous care topics">{ARROW}</button><button class="round-button next" type="button" data-scroll-rail="concern-rail" data-direction="1" aria-label="Next care topics">{ARROW}</button></div></div>{concern_cards(True)}</div></section>'''
    barrier=f'''<section class="section compact"><div class="wrap barrier"><div>{eye('The first barrier')}<h2>Looking for therapy can ask too much of the person <em>already carrying too much.</em></h2><p>Names, biographies, credentials, insurance, availability, treatment styles—traditional searches can leave you comparing dozens of details before you know which ones will matter in the room.</p><p>Doppler makes that first decision more human.</p></div><div class="signal-box" aria-label="Doppler listens for what matters to you"><span class="signal-ring"></span><span class="signal-ring"></span><span class="signal-ring"></span><span class="signal-tag">The details. The context. The person.</span><div class="signal-core"><small>Doppler listens for</small><strong>What matters to you</strong></div><span class="signal-tag">A clearer place to begin</span></div></div></section>'''
    matching=f'''<section class="section"><div class="wrap two-col"><div>{eye('How Doppler starts differently','dot')}<h2>Doppler listens for the details that can <em>shape trust.</em></h2><p class="lead">Availability matters. It simply is not the whole decision.</p><div class="actions">{a('See the complete matching approach','our-approach')}</div></div>{match_panel()}</div></section>'''
    steps=[('Before reaching out','It has been building.','The worry follows you into bed. Your patience is thinner. Small decisions take more energy than they should. You keep waiting for life to calm down first.'),('The decision','You stop trying to explain it perfectly.','You tell Doppler what has been difficult, what kind of conversation may feel useful, and whether care from home or in person fits your life better.'),('The introduction','The match begins with more context.','Your needs and preferences help shape the starting point, together with practical considerations such as location, eligibility, and availability.'),('Beyond the session','Then the work meets you in real life.','A difficult moment still comes. But you may recognize the pattern sooner, create a pause before the familiar reaction, and bring another choice into the moment.')]
    stages=''.join(f'<article class="journey-step {"is-current" if i==0 else ""}" data-journey-step="0{i+1}" data-journey-label="{label.upper()}">{eye(label)}<h3>{title}</h3><p>{copy}</p>{a("See mindfulness in care","mindfulness") if i==3 else ""}</article>' for i,(label,title,copy) in enumerate(steps))
    journey=f'''<section class="section journey"><div class="wrap"><div class="section-head"><div>{eye('What the path can feel like','dot')}<h2>Support begins to matter when it reaches <em>the life you actually live.</em></h2><p class="lead">The goal is not a perfectly calm life. It is more understanding, more support, and more choice when difficult moments arrive.</p></div></div><div class="journey-grid"><div class="journey-visual">{image('contact','Illustrated person approaching a calm, plant-filled threshold')}<div class="journey-caption"><span data-journey-label>BEFORE REACHING OUT</span><span data-journey-number>01 / 04</span></div></div><div class="journey-stages">{stages}</div></div></div></section>'''
    setting=f'''<section class="section"><div class="wrap"><div class="section-head"><div>{eye('Care without rearranging your life','dot')}<h2>One relationship.<br><em>Two ways to meet.</em></h2><p class="lead">Choose the setting that makes it easier to keep showing up.</p></div></div>{settings()}</div></section>'''
    bridge=f'''<section class="bridge"><div class="bridge-art">{image('pool','Quiet water and a seated person in a botanical courtyard')}</div><div class="wrap"><div class="bridge-copy">{eye('Where therapy meets the moment','dot')}<h2>Therapy can help you understand the pattern.<em>Mindfulness can help you notice it while it is happening.</em></h2><p>Mindfulness is not about emptying your mind or remaining calm all the time. It is the practice of noticing thoughts, emotions, and body signals with less automatic judgment.</p></div></div></section>'''
    clarity=f'''<section class="section clarity-section"><div class="wrap two-col"><div>{eye('Know what happens before you commit','dot')}<h2>Care should feel clear before <em>the first conversation.</em></h2><p class="lead">The process should answer practical questions—not create more of them.</p><div class="actions">{a('Review coverage questions','insurance')}</div></div><div>{eye('What you can ask about')}{faqs([('Matching context','Your needs and preferences help shape the starting point.'),('Format and availability','At-home and in-person options depend on location and clinician availability.'),('Virtual-care privacy','Ask how the platform, privacy practices, and backup plan work before you connect.'),('Coverage and cost','Confirm network status, deductible, copay, and telehealth coverage before care.')])}</div></div></section>'''
    journal=f'''<section class="section"><div class="wrap"><div class="section-head"><div>{eye('Support between appointments','dot')}<h2>Useful guidance for the moments that <em>do not wait for a session.</em></h2></div>{a('Read all eight guides','journal')}</div>{journal_cards(ARTICLES[:3],True)}</div></section>'''
    return hero+proof+before+barrier+matching+journey+setting+bridge+pause_section()+clarity+journal+ready()

def section(content, cls=''): return f'<section class="section {cls}"><div class="wrap">{content}</div></section>'

def approach():
    return subhero('A thoughtful match gives therapy a more <em>personal start.</em>','Doppler uses the background and preferences you share to begin a more thoughtful introduction.','Our approach')+section(f'<div class="two-col"><div>{eye("Context first / person always","dot")}<h2>Not just a name.<br><em>A place to begin.</em></h2><p class="lead">The concerns you bring, the way you want to work, and the practical shape of your life all belong in the conversation.</p><p class="spaced">A first introduction is a starting point—not a promise that every relationship will be the right fit. Your experience matters as care develops.</p></div>{match_panel()}</div>')+section(card_grid([('Tell us what matters.','Begin with the questionnaire. Share the needs and preferences you want Doppler to understand.'),('Clarify the practical fit.','Discuss location, format, availability, eligibility, and costs before care begins.'),('Keep the conversation open.','Talk with your clinician and the team about the relationship, your goals, and what is or is not working.')]))+ready()

def mindfulness():
    return subhero('A quieter moment can begin <em>before everything is solved.</em>','Notice what is here. Let your shoulders soften. Choose an anchor that feels comfortable, or choose not to practice today.','Mindfulness, without pressure','pool','lavender','A PRACTICE SHAPED AROUND YOU',a('Open the tools room','tools','button'))+section(f'<div class="two-col"><div>{eye("More choice in the moment","dot")}<h2>Calm is not the <em>price of admission.</em></h2><p class="lead">The aim is not to empty your mind or stay calm all the time. It is to become a little more aware of what is here before the next automatic reaction.</p><p class="spaced">When it fits your care, you and your clinician can discuss whether grounding, breathing, reflection, or meditation might be useful. You can always ask for another approach.</p></div><div class="hero-frame">{image("sanctuary","Illustrated architectural meditation sanctuary")}</div></div>')+section(card_grid([('Notice sooner.','You can begin by noticing a thought, feeling, or body signal without having to change it immediately.'),('Create a pause.','Choose a small, manageable practice—or simply stop for a moment and look around.'),('Choose what follows.','Bring what you notice back into a conversation about your needs, goals, and next steps.')]))+section(f'<div class="copy-block"><h2>A practice should make room for you.</h2><p>These website exercises are general-wellness tools, not a substitute for assessment or treatment. Meditation and mindfulness can feel uncomfortable for some people. Do not use them to postpone needed care.</p><p>Stop any exercise that increases distress. Ask a qualified professional about an approach that fits your circumstances.</p><p class="source-note">Background: <a href="{NCCIH}" target="_blank" rel="noopener noreferrer">NCCIH — Meditation and mindfulness: effectiveness and safety.</a></p>{a("Explore the tools","tools","button")}</div>')+ready()

def meeting(home=True):
    title='Your own room.<br><em>Time set aside for you.</em>' if home else 'A separate space.<br><em>Room for a real conversation.</em>'
    copy='Meet by video without adding a commute or another transition to the day. Confirm the details of virtual care before you begin.' if home else 'For some people, leaving the everyday setting helps create space for a conversation. Ask about the in-person options available to you.'
    cards=[('Choose your space.','Consider a private, comfortable place where you can speak without being overheard.'),('Know the connection.','Confirm the video platform, appointment link, and backup plan if the connection drops.'),('Confirm eligibility.','Care depends on your location, age, clinical needs, and a clinician authorized to work where you are.')] if home else [('Ask about location.','Confirm where appointments take place and whether travel and access work for you.'),('Discuss what helps.','Share accessibility needs and preferences that would make the setting more workable.'),('Protect the time.','Ask about scheduling, costs, and appointment policies before you begin.')]
    return subhero(title,copy,'At-home therapy' if home else 'In-person therapy','at-home' if home else 'in-person','ivory','ONE RELATIONSHIP / YOUR SETTING')+section(card_grid(cards))+section(f'<div class="two-col"><div>{eye("Care should fit real life","dot")}<h2>Make the practical questions <em>part of the conversation.</em></h2><p class="lead">A convenient format is useful only when it also fits your privacy, comfort, and care needs. Ask about what is available rather than assuming one setting works for everyone.</p></div>{faqs(FAQ[1:2]+FAQ[3:5])}</div>')+ready()

def mission():
    return subhero('Care should begin with <em>the person.</em>','Finding help should not feel like another job. Doppler’s starting point is the person behind the appointment: their needs, preferences, and everyday life.','Our mission','contact','mint','THE PERSON / BEFORE THE PROCESS')+section(f'<div class="copy-block"><h2>A more human place to start.</h2><p>People arrive at therapy with different stories, different pressures, and different ideas about what help could look like. Some know exactly what they want to talk about. Others only know that something has become harder.</p><p>Our approach makes room for both. The information you choose to share helps shape a thoughtful starting point, rather than reducing the decision to an open time slot.</p><h2>Support that reaches everyday life.</h2><p>The goal is not a perfectly calm life. It is more understanding, more support, and more choice when difficult moments arrive. At-home and in-person options are ways to make that work more accessible when location, eligibility, and availability allow.</p></div>')+section(card_grid([('Person first.','Your context, preferences, and goals belong at the beginning.'),('Clear next steps.','The practical questions about care deserve direct answers.'),('Room to choose.','The relationship and the approach can be discussed as your needs become clearer.')]))+ready()

def tools():
    info=[('Breathing','A gentle visual cue.','Follow a comfortable rhythm for about 30 seconds or one minute. Text-only mode is available.','breathing'),('Grounding','Come back to the room.','Move through a flexible five-senses prompt at your own pace. Skip or adapt any step.','grounding'),('Reflection','Make room for the words.','An optional prompt and a space to write. Your words are not sent or saved by this website.','reflection'),('Quiet time','Nothing to perform.','A silent timer for one, three, or five minutes. Start, pause, or stop whenever you need.','quiet-time')]
    grid='<div class="tool-grid">'+''.join(f'<article class="tool-card">{eye(label,"purple")}<h3>{title}</h3><p>{copy}</p>{a("Open "+label.lower(),"tools/"+slug,"button")}</article>' for label,title,copy,slug in info)+'</div>'
    return subhero('A little more space.<br><em>A little less pressure.</em>','Choose an anchor that feels workable today. You do not have to use your breath, close your eyes, or complete an exercise.','The tools room','pool','lavender','NOTICE / PAUSE / CHOOSE',a('Start a gentle pause','tools/breathing','button'))+section(grid+'<div class="note">These are optional general-wellness exercises, not medical treatment or an emergency service. Stop if you feel uncomfortable. A clinician can help you decide what belongs in your care.</div>')+ready()

def tool_page(kind):
    descriptions={'breathing':('One easy breath.<br><em>Then the next.</em>','A gentle visual anchor, with no breath holds and no need to follow a pace that feels uncomfortable.'),'grounding':('Come back to <em>the room around you.</em>','Move through five small prompts at your own pace. Adapt each one to your senses and comfort.'),'reflection':('Start with <em>what feels true.</em>','A private space in this tab for unfinished thoughts. Nothing you type here is sent to Doppler or saved by this website.'),'quiet-time':('Time without <em>another task.</em>','Choose a little quiet time. There is nothing you have to achieve before the timer ends.')}
    title,description=descriptions[kind]
    hero=subhero(title,description,'Doppler / '+kind.replace('-',' '),None,'lavender',cta=a('All mindfulness tools','tools'))
    if kind=='breathing': content=breath_tool()
    elif kind=='grounding':
        content=f'''<div class="interactive-panel" data-grounding><div class="ground-progress" data-ground-progress aria-hidden="true"><i class="on"></i><i></i><i></i><i></i><i></i></div><div class="ground-number" data-ground-number aria-hidden="true">5</div><h2 data-ground-heading>Find five things you can see.</h2><p class="lead" data-ground-copy>Keep your eyes open. Let your gaze rest on a shape, a color, a line, a light, or a familiar object.</p><div class="actions"><button class="button" type="button" data-ground-next>Next gentle step</button><button class="button outline" type="button" data-ground-back disabled>Previous step</button></div><p class="small">You can skip, adapt, or stop at any point. No answers are recorded.</p></div>'''
    elif kind=='reflection':
        content=f'''<div class="interactive-panel" data-reflection>{eye('No need to get the words right','purple')}<h2 id="reflection-prompt" data-reflection-prompt>What feels hardest to carry today, and what would make it one small degree lighter?</h2><label class="sr-only" for="reflection-words">Your reflection</label><textarea id="reflection-words" aria-describedby="reflection-privacy" autocomplete="off" spellcheck="false" placeholder="Begin anywhere. Or just sit with the question." maxlength="15000"></textarea><p id="reflection-privacy" class="small">Only in this tab. No account, autosave, or submission. Closing or leaving the page clears your writing. Your browser or extensions may have their own behavior.</p><p class="small" data-word-count>0 words · not sent or saved</p><div class="actions"><button class="button outline" type="button" data-new-prompt>Another prompt</button><button class="quiet-button" type="button" data-clear-reflection>Clear my writing</button></div></div>'''
    else:
        content='''<div class="interactive-panel center" data-meditation><span class="eyebrow purple">Quiet time</span><h2>A moment that belongs to you.</h2><p>Let your attention rest on a comfortable, ordinary detail. Eyes open or closed—whichever feels better.</p><div class="timer-face" data-timer-face aria-label="Time remaining">1:00</div><div class="timer-inputs"><label for="quiet-duration">Time</label><select id="quiet-duration" data-timer-duration><option value="60">One minute</option><option value="180">Three minutes</option><option value="300">Five minutes</option></select></div><div class="actions" style="justify-content:center"><button class="button" type="button" data-timer-start>Start quiet time</button><button class="button outline" type="button" data-timer-reset>Reset</button></div><p class="small" data-timer-status aria-live="polite">Silent by default. No bell or automatic audio.</p></div>'''
    return hero+section(content)+section(f'<div class="copy-block center"><h2>Another anchor is always an option.</h2><p>These are general-wellness tools, not treatment. Stop if a practice feels uncomfortable or increases distress.</p>{a("Return to the tools room","tools","button outline")}</div>')

def journal():
    buttons=''.join(f'<button class="filter-button" type="button" data-journal-filter="{category}" aria-pressed="{str(category=="All").lower()}">{category}</button>' for category in ['All','Anxiety','Grounding','Therapy','Life'])
    return subhero('For the moments <em>between appointments.</em>','Short guides, simple prompts, and practical questions to bring into everyday life.','The Doppler journal',None,'ivory',cta=a('Explore mindfulness tools','tools'))+section(f'<div class="search-row"><label class="sr-only" for="journal-search">Search guides</label><input id="journal-search" type="search" placeholder="Find a guide…" data-journal-search><div class="filter-group" aria-label="Filter guides">{buttons}</div></div><p class="small" data-search-status aria-live="polite">8 guides</p><div class="space-top">{journal_cards(ARTICLES)}</div><p class="no-results" data-no-results hidden>No guides match that search. Try another word or choose All.</p>')+ready()

def article(item):
    copy=''.join(f'<h2>{heading}</h2><p>{text}</p>' for heading,text in item['sections'])
    if item['source']:
        copy+=f'<p class="source-note">Background resource: <a href="{item["source"]}" target="_blank" rel="noopener noreferrer">{"NCCIH — Meditation and mindfulness: effectiveness and safety" if item["source"]==NCCIH else "NIMH — Psychotherapies"}</a>. The exercise or reflection above is an editorial prompt, not a validated clinical protocol.</p>'
    else: copy+='<p class="source-note">General reflection and practical questions—not a diagnosis, clinical screening, or treatment protocol. Discuss individual care needs with a qualified professional.</p>'
    return f'''<header class="article-header"><div class="wrap"><div class="breadcrumb">{a('Journal','journal','',False)}<span>/</span><span>{item['category']}</span></div>{eye(item['category']+' / short guide','purple')}<h1>{item['title']}</h1><p>{item['intro']}</p>{image(item['image'],'Illustrative Doppler wellness scene','article-cover',True)}</div></header><section class="section compact"><div class="wrap article-layout"><article class="copy-block">{copy}</article><aside class="article-aside">{eye('A practical next step')}<p>You do not have to have the right words before asking for help.</p><div class="actions">{quiz_button(cls='button small-button')}</div><div class="space-top">{a('Explore mindfulness tools','tools')}</div></aside></div></section>'''+ready()

def contact():
    return subhero('Choose the path that gets you to <em>the right place.</em>','For general questions, email the Doppler team. For care-related information, use the patient intake form instead of ordinary email.','Contact','contact','mint','CLEAR ROUTING / LESS FRICTION')+section(f'''<div class="contact-grid"><div class="surface contact-card">{eye('General questions')}<a class="email-feature" href="mailto:{EMAIL}">{EMAIL}</a><p class="lead">Questions about the starting process, formats, or where to go next? Email the team for general information.</p><p class="small spaced">Please do not include sensitive health information, insurance documents, or urgent requests in ordinary email.</p></div><div class="contact-routes"><div class="route-card"><h3>Looking for care?</h3><p>Start with the matching questionnaire or use the patient intake form for care-related information.</p>{quiz_button('Take the quiz','text-link')}{a('Patient intake',CONFIG['patient_intake_url'])}</div><div class="route-card"><h3>For clinicians.</h3><p>Learn about working with Doppler and reach the clinician application.</p>{a('Explore clinician opportunities','for-clinicians')}</div></div></div>''')

def clinicians():
    return subhero('Meaningful care begins with <em>meaningful relationships.</em>','Bring your expertise to a practice focused on thoughtful introductions and care shaped around the individual.','For clinicians','approach','ivory','YOUR EXPERTISE / THE PERSON',a('Open the clinician application',CONFIG['clinician_application_url'],'button'))+section(card_grid([('Thoughtfully matched referrals.','Discuss how your expertise and preferred areas of care align with client needs.'),('Flexible care settings.','Explore the virtual and in-person formats available within the practice and your licensure.'),('A conversation about fit.','Ask about administrative support, caseload expectations, scheduling, and the practical terms of working together.')]))+section(f'<div class="two-col"><div>{eye("A considered next step","dot")}<h2>Make room for the way <em>you work best.</em></h2><p class="lead">Your clinical approach, experience, and preferences belong in the conversation, too.</p></div><div class="surface contact-card"><h3>Start with an introduction.</h3><p class="spaced">Use the existing clinician application or contact the team with general questions about opportunities. Current openings and terms should be confirmed directly.</p><div class="actions">{a("Clinician application",CONFIG["clinician_application_url"],"button")}{a("Email the team","mailto:"+EMAIL)}</div></div></div>')

def insurance():
    questions=[('Is this clinician in network for my plan?','Confirm the exact provider and plan, not just the insurance company name.'),('What could I owe?','Ask about your remaining deductible, copay or coinsurance, self-pay rates, and any other fees that may apply.'),('Does the format change my coverage?','Ask whether your plan covers the intended session format, including telehealth, and whether there are requirements to complete first.'),('What should I do before the first appointment?','Confirm benefits and payment arrangements with the team and your insurer. Use an appropriate intake channel for insurance documents rather than ordinary email.')]
    return subhero('Clearer questions.<br><em>Fewer surprises.</em>','Coverage and cost should be part of the conversation before care begins. Ask the team to help you understand the next step for your situation.','Insurance & cost',None,'lavender',cta=a('Ask a coverage question','mailto:'+EMAIL,'button'))+section(f'<div class="two-col"><div>{eye("Know before you commit","dot")}<h2>Confirm the details that <em>apply to you.</em></h2><p class="lead">Insurance participation and benefits vary by plan, clinician, location, and service. A general website statement cannot confirm your individual coverage.</p><div class="actions">{a("Contact the Doppler team","contact")}</div></div>{faqs(questions)}</div>')+ready()

def questions():
    return subhero('The questions are <em>part of beginning.</em>','Get a clearer picture of matching, care settings, coverage, and the practical next step.','Questions',None,'ivory',cta=a('Ask the team','contact','button'))+section(f'<div class="copy-block">{faqs(FAQ)}</div>')+ready()

def quiz_landing():
    return subhero('Start with what has <em>been difficult.</em>','The matching questionnaire is a first step, not a diagnosis. Share the context and preferences you want Doppler to understand.','Your next step',None,'lavender',cta=quiz_button('Open the matching questionnaire'))+section(f'<div class="two-col"><div><h2>A little context.<br><em>A more personal start.</em></h2><p class="lead">You will continue to Doppler’s existing questionnaire on Jotform. The form’s own privacy terms and settings apply. This website does not collect or relay your answers.</p><p class="small spaced">Eligibility, availability, costs, and the next steps should be confirmed before care begins. The form is not an emergency service.</p></div>{card_grid([("Choose what to share.","Explain what has become harder and how you would prefer to work.")])}</div>')

def care():
    return subhero('You do not need a perfect label.<br><em>Start with what feels true.</em>','Explore some of the concerns people bring to a first conversation. These pages are starting points—not diagnostic guidance.','Care',None,'ivory')+section(concern_cards())+ready()

def concern(item):
    slug,label,heading,copy,img,prompts=item
    body=f'<div class="two-col"><div>{eye("A starting conversation","dot")}<h2>You can begin <em>in your own words.</em></h2><p class="lead">{copy}</p><p class="spaced">You do not have to answer every question or explain the whole story at once. Share what you want a clinician to understand, including what would help the conversation feel more comfortable.</p></div><div class="match-panel">{eye("Questions you might bring")}{"".join(f"<h4 class=spaced>{p}</h4>" for p in prompts)}</div></div>'
    caution='The information here cannot determine which care is appropriate for you. Discuss assessment, options, and next steps with a qualified professional.'
    if slug=='substance-use': caution+=' For urgent withdrawal symptoms, overdose, or another medical emergency, seek emergency medical help. Do not use a website exercise as a detox or withdrawal plan.'
    if slug=='relationships': caution+=' If you are afraid of someone or there is abuse, prioritize safety and individual professional support rather than an ordinary communication exercise.'
    return subhero(heading.replace('.', '',1)+' <em>There is room to talk.</em>',copy,label,img,'ivory','YOUR CONTEXT / YOUR PACE')+section(body)+section(f'<div class="copy-block"><div class="note">{caution}</div><h2>Make the practical fit clear.</h2><p>Ask about the clinician’s approach, your goals, the setting, and the cost. Availability and eligibility depend on your individual circumstances.</p>{a("How matching begins","our-approach","button outline")}</div>')+ready()

def privacy():
    return subhero('A note about <em>this website.</em>','This page describes the behavior of this static website. It is not a clinical Notice of Privacy Practices or a statement about every external service.','Website privacy',None,'ivory',cta=a('Contact the team','contact'))+section(f'''<div class="copy-block"><h2>Interactive tools stay in your tab.</h2><p>The mini-quiz, reflection space, breathing exercise, and timers run locally in your browser. This site’s code does not send your tool entries to a server, save them to local storage, or attach them to external form links. Leaving the page clears in-memory writing and selections.</p><h2>External forms are separate.</h2><p>The questionnaire, patient intake, and clinician application open external Jotform pages. Information entered there is handled by those services and the form operator, under their own settings and notices. Review those before submitting sensitive information.</p><h2>Hosting and your browser.</h2><p>This package does not include advertising pixels, analytics scripts, tracking cookies, or third-party font requests. A hosting provider may still process ordinary connection information, such as IP addresses and request logs. Your browser, sync settings, or extensions may also process information independently of this site.</p><h2>Clinical records and sensitive information.</h2><p>For questions about clinical records, privacy rights, or the practice’s formal privacy notice, contact the Doppler team. Do not send sensitive health information through ordinary email. Use an appropriate intake or clinical communication channel.</p><p>{a(EMAIL,'mailto:'+EMAIL)}</p></div>''')

def accessibility():
    return subhero('A clearer way <em>through the website.</em>','Different people use different devices, senses, and ways of navigating. The interface includes options intended to make the essentials easier to reach.','Accessibility',None,'ivory',cta=a('Report a website barrier','mailto:'+EMAIL,'button'))+section('<div class="copy-block"><h2>Navigation and controls.</h2><p>Links and buttons can be reached with a keyboard. The page includes a skip link, visible focus indicators, labeled controls, and a collapsible mobile menu. Care and matching tabs can be operated with arrow keys.</p><h2>Motion and mindful tools.</h2><p>The breathing exercise includes text-only cues. A reduced-motion preference turns off decorative animation. Exercises are optional, do not start automatically, and can be paused or reset. Timers pause when the tab is hidden.</p><h2>Tell us about a barrier.</h2><p>To report a problem, email the team with the page and what you were trying to do. Share the device or browser if useful; do not include sensitive clinical information. This page describes interface features, not a certification of compliance with a particular standard.</p></div>')

def not_found():
    return f'<section class="page-404"><div class="wrap">{eye("404 / a different starting point")}<h1>This page isn’t here.<br><em>You still have a way forward.</em></h1><p class="lead spaced">Return to the homepage or contact the Doppler team.</p><div class="actions">{a("Back to the homepage","","button")}{a("Contact","contact")}</div></div></section>'

def add(route,title,desc,body_fn,provenance='Newly written reconstruction based on saved navigation, homepage copy, and screenshots; not recovered original source.'):
    global ROUTE
    ROUTE=route
    body=body_fn()
    pub=CONFIG.get('public_url','').rstrip('/')
    indexing=bool(pub and CONFIG.get('allow_indexing'))
    canonical=f'{pub}/{route+"/" if route else ""}' if pub else ''
    meta_canonical=f'<link rel="canonical" href="{E(canonical)}"><meta property="og:url" content="{E(canonical)}">' if canonical else ''
    org={'@context':'https://schema.org','@type':'Organization','name':'Doppler Wellness','email':EMAIL}
    if pub: org.update(url=pub,logo=pub+'/assets/mark.svg')
    robots='index,follow' if indexing and route!='404' else 'noindex,nofollow'
    document=f'''<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>{E(title)} | Doppler Wellness</title><meta name="description" content="{E(desc,quote=True)}"><meta name="theme-color" content="#fffdf3"><meta name="robots" content="{robots}"><meta name="referrer" content="no-referrer"><meta property="og:type" content="website"><meta property="og:title" content="{E(title,quote=True)} | Doppler Wellness"><meta property="og:description" content="{E(desc,quote=True)}">{meta_canonical}<link rel="icon" href="{asset('assets/mark.svg')}" type="image/svg+xml"><link rel="stylesheet" href="{asset('assets/site.css')}"><script defer src="{asset('assets/site.js')}"></script><script type="application/ld+json">{json.dumps(org,ensure_ascii=False)}</script></head>
<body data-page="{E(route or 'home')}">{nav()}<noscript><div class="nojs-note">The questionnaire and footer links remain available. Enable JavaScript for the mobile menu and optional interactive tools. {a('Open Doppler’s questionnaire',CONFIG['quiz_url'],'',False)}</div></noscript><main id="main" tabindex="-1">{body}</main>{footer()}</body></html>'''
    path=ROOT / route / 'index.html' if route else ROOT/'index.html'
    path.parent.mkdir(parents=True,exist_ok=True)
    path.write_text(document,encoding='utf-8')
    PAGES[route or '/']={'title':title,'file':str(path.relative_to(ROOT)),'provenance':provenance}

ASSETS = json.loads((ROOT/'docs/ASSET_PROVENANCE.json').read_text())
add('', 'Therapy, with room to breathe', 'Thoughtfully matched therapy with at-home and in-person options. Find a starting point that makes room for your life.', home, 'Most homepage wording and section order recovered from the saved site text. Layout, CSS, JavaScript, vector logo, and interactions reimplemented from screenshots; no gray fade over the pause section. Unsupported rating and client-count claims omitted.')
add('our-approach','A thoughtful match','How context and preferences shape a thoughtful starting point for therapy.',approach)
add('mindfulness','Mindfulness, without pressure','A quieter moment can begin before everything is solved.',mindfulness)
add('at-home-therapy','At-home therapy','Your own room. Time set aside for you. Explore video therapy and questions to ask before care.',lambda:meeting(True))
add('in-person-therapy','In-person therapy','A separate space and a conversation just for you. Ask about in-person care options.',lambda:meeting(False))
add('mission','Care should begin with the person','The Doppler approach to a more human place to start.',mission)
add('tools','The mindfulness tools room','Optional breathing, grounding, reflection, and quiet-time tools.',tools)
for kind in ['breathing','grounding','reflection','quiet-time']:
    add('tools/'+kind,kind.replace('-',' ').title(), 'Optional general-wellness '+kind.replace('-',' ')+' practice, at your own pace.',lambda k=kind:tool_page(k),'New functional implementation. Breathing tool labels and general concept recovered from saved home copy; other tool details recreated. No clinical-protocol validation claimed.')
add('journal','For the moments between appointments','Eight short guides and practical reflection prompts.',journal)
for item in ARTICLES:
    add('journal/'+item['slug'],item['title'],item['intro'],lambda x=item:article(x),'Rewritten guide body, not recovered original article. First three titles recovered from saved site text; remaining titles and all guide bodies newly written for this reconstruction. Requires owner / clinical review before publication.')
add('contact','Choose the right path','Contact Doppler for general questions, patient intake, or clinician opportunities.',contact)
add('for-clinicians','For clinicians','Explore working with Doppler and reach the existing clinician application.',clinicians)
add('insurance','Insurance and cost','Questions to ask about coverage, cost, and the practical next step.',insurance)
add('questions','Questions before care','Answers and practical questions about matching, format, and starting care.',questions)
add('quiz','Start your matching questionnaire','Open the existing Doppler matching questionnaire.',quiz_landing)
add('care','Start with what feels true','Explore concerns people bring to a first therapy conversation.',care)
for item in CONCERNS: add('care/'+item[0],item[1],item[2]+' '+item[3],lambda x=item:concern(x))
add('privacy','Website privacy','How this static website’s interactive tools and external links work.',privacy,'New description of this package’s actual behavior; not a recovered clinical privacy policy or legal notice.')
add('accessibility','Accessibility','Keyboard navigation, reduced motion, and ways to report a barrier.',accessibility,'New description of implemented interface features; not a compliance certification.')
# A real 404 page with root-relative paths resolved against the site deployment base.
add('404','Page not found','Return to a useful starting point at Doppler.',not_found)
# Keep 404.html usable with GitHub project Pages, including nested unknown paths.
notfound=(ROOT/'404/index.html').read_text().replace('../','./')
base_script='''<script>(function(){var p=location.pathname;var base=p.indexOf('/doppler/')===0?'/doppler/':'/';var b=document.createElement('base');b.href=base;document.head.prepend(b)})();</script>'''
notfound=notfound.replace('<head>','<head>'+base_script,1)
(ROOT/'404.html').write_text(notfound)
(ROOT/'.nojekyll').write_text('')
(ROOT/'robots.txt').write_text('User-agent: *\nDisallow: /\n' if not (CONFIG.get('allow_indexing') and CONFIG.get('public_url')) else 'User-agent: *\nAllow: /\n')
if CONFIG.get('public_url') and CONFIG.get('allow_indexing'):
    base=CONFIG['public_url'].rstrip('/')
    (ROOT/'sitemap.xml').write_text('<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">'+''.join(f'<url><loc>{E(base+("/" if r=="/" else "/"+r+"/"))}</loc></url>' for r in PAGES if r!='404')+'</urlset>')
else:
    (ROOT/'sitemap.xml').unlink(missing_ok=True)
(ROOT/'docs/PAGE_PROVENANCE.json').write_text(json.dumps(PAGES,ensure_ascii=False,indent=2)+'\n')
print(f'Built {len(PAGES)} page routes plus 404.html. Indexing: {"ON" if CONFIG.get("allow_indexing") and CONFIG.get("public_url") else "OFF (review copy)"}.')
